### ISSUE TITLE
Todo checked mark broken on El Capitan

### ISSUE THREAD

**Issue by mutahhir** [mutahhir/foldingtext-issues#10]
![Image](http://f.cl.ly/items/0E072S2w3J2m3e3U163L/Screen%20Shot%202015-10-13%20at%208.52.58%20AM.png)

**Comment by jessegrosjean** [comment]
I've got a lead on this one. I don't see the problem generally... but I DO see the problem if I install and enable this version of Source Code Pro that was installed on my computer:

https://www.dropbox.com/s/tarulmskfnngpa1/Source%20Code%20Pro.zip?dl=0

You can recreate by:
1. Delete any versions of source code pro font that you've installed.
2. Install this version and you should see the bug.
3. Enable/Disable this version and you'll see the bug show/hide instantly as FoldingText sits open.

But if I download the latest source code pro from the web I don't see the problem.

Would be interesting to know why!  Things to note:
1. Source Code Pro IS the font FoldingText uses to draw the checkboxes.
2. FoldingText includes an embedded version of Source Code Pro
3. I guess if you have a system installed version of a font it overrides the version included in your app?... seems odd, would have expected the other way around.
4. This "broken" version of Source Code Pro that I've linked to does seem to include the proper checkbox glyphs.

**Comment by jessegrosjean** [comment]
Seems to verify that system version of a font overrides any font that you include in your app:

http://stackoverflow.com/questions/32403858/how-to-override-system-fonts-in-os-x

**Comment by rozling** [comment]
Hi, I'm having this issue - it's a pain because I have eye problems and find Source Code Pro by far the most comfortable font to do the bulk of my coding with, so I really don't want to uninstall it.  A fix would be greatly appreciated!
