### ISSUE TITLE
Blank line incorrectly rendered under a line of text that just fits on one line, but ends with bold.

### ISSUE THREAD

**Issue by dlehman** [mutahhir/foldingtext-issues#2]
If you have a long line of text that _just fits_ on to one line, and the line ends with bold/italics, a blank line is incorrectly rendered under that line of text.

This video demonstrates the incorrect rendering.
https://dl.dropboxusercontent.com/u/110859/ft-incorrect-blank-line.mp4

**Comment by mutahhir** [comment]
I see what you mean, but the only way simple way I know to fix this would impact selections, so, unfortunately, I think this cannot be fixed with the current design of FoldingText. (But, full disclosure, I don't know what a solution would look like even if we did do the redesign)
