### ISSUE TITLE
Only first level items are rendered as todo item in todo mode.

### ISSUE THREAD

**Issue by mmzsource** [mutahhir/foldingtext-issues#3]
Noticed that only toplevel items in todo mode are rendered as todo. So:
# Foo.todo
- Rendered with clickable todo box
  - rendered as listitem without todo box
  - rendered as listitem without todo box
- Rendered with clickable todo box

I really hope this is not a new feature, because the hierarchical todo-list is my favorite foldingtext feature.

**Comment by mutahhir** [comment]
Can you paste within ` ` ` `<text>` ` ` ` (as code, since github process markdown in comments) the actual markdown you used? Also, have you taken a look at [this](http://support.foldingtext.com/t/can-i-have-bullet-points-under-a-todo/347/15) discussion?

**Comment by mmzsource** [comment]
Wasn't aware of that discussion. Experimented with the options discussed. In the 2.1 Dev (749) version, only toplevel items are rendered as todo boxes:

```
"-" Todolist.todo

- firstlevel item
    - secondlevel item
- firstlevel item

"*" Todolist.todo

* firstlevel item
    * secondlevel item
* firstlevel item

"+" Todolist.todo

+ firstlevel item
    + secondlevel item
+ firstlevel item
```

Renders as shown in attached image. Unfortunately this behaviour forces me to keep working in the old release since hierarchical todo's are why I bought foldingtext. Foldingtext would become nearly useless to me if this feature is dropped.

<img width="431" alt="screen shot 2015-08-15 at 11 34 31" src="https://cloud.githubusercontent.com/assets/386764/9288348/954de8c2-4342-11e5-8298-aee599ddc476.png">

**Comment by mmzsource** [comment]
Any updates on this issue? Would like to update to version 2.1 via the app store, but first want to be sure if hierarchical todo's still work.

**Comment by mutahhir** [comment]
Sorry, somehow this issue wasn't closed by me. Hierarchial todos should work as you expect withing Ft 2.1 release. I'm attaching a screenshot similar to your above snippet:

![screen shot 2015-10-24 at 9 08 13 am](https://cloud.githubusercontent.com/assets/573531/10708810/cf7b5eb2-7a2e-11e5-92a1-7df928c39041.png)
