### ISSUE TITLE
.schedule mode not stepping beyond the first step. no notifications.

### ISSUE THREAD

**Issue by mmzsource** [mutahhir/foldingtext-issues#4]
The new schedule mode seems to be starting the first step I click on (start time appears), but doesn't step to the next step. The time which is rendered right before the next step is never highlighted and there are no OS notifications of the first step ending although my notification settings for the current release and the dev release are identical.

**Comment by jacobsamlarose** [comment]
Hey Mutahir— is this actually fixed? I'm on DEV 749, and just tried the schedule mode again. First item in my schedule list fired a notification, the rest haven't...
