### ISSUE TITLE
"New Document" focus

### ISSUE THREAD

**Issue by p-s-** [mutahhir/foldingtext-issues#7]
clicking "New Document" via the menu on the dock icon should focus the new opened file

thanks for all the work,
and continuing FT <3

**Comment by mutahhir** [comment]
Thanks for reporting this. I cannot reproduce this on my machine. I'm on OS X 10.10.5 and FT 2.1 Dev (749). Can you maybe explain a bit more?

**Comment by p-s-** [comment]
You are right, I'm sorry for not providing details.
(I was on 10.10.4 with the current App Store version), now I tried with 10.10.5 and 2.1 Dev (749) on a Macbook Air.
I tap with two fingers on the FT icon in my dock and tap on "New Document". The new file gets opened, but only "behind" the current active application, so i have to tap the FT icon with one finger again to bring it to the top/in focus.
In, say Firefox, it doesn't matter if another application is curently active; when I do the "new window" thing it gains focus automatically

Hope this makes sense, hope it's not only on my machine, hope it's not too minor : )

(The current dev version opens extremely fast for me, it's great! But does it somehow copy my licence from the app store? May I keep using it?)

**Comment by mutahhir** [comment]
I didn't get that you were trying to open a new document while keeping the FoldingText in the background. Sorry, yes, I can reproduce this behavior. 

However, we're not doing anything special with this, and are using the default cocoa mechanism for creating new documents. You can reproduce this behavior for most apps that use an NSDocument based app structure.
